"""Long sample ticket description for ML summarizer demos and optional tests."""

ML_SAMPLE_TICKET_DESCRIPTION = (
    "Our engineering team has been unable to access the staging environment since "
    "Tuesday morning after the scheduled maintenance window completed. When we "
    "attempt to log in through the SSO portal, we receive a generic authentication "
    "failed message even though the same credentials work for production dashboards "
    "and other SaaS tools on the same identity provider. We have cleared browser "
    "caches, reproduced the issue in incognito mode, and confirmed with internal IT "
    "that our accounts were not disabled during the maintenance rollout. "
    "The outage is blocking validation of a hotfix for a payment processing defect "
    "that affects enterprise customers who pay via invoice rather than credit card. "
    "Finance has already received escalation from two accounts whose renewals depend "
    "on the fix shipping this week. QA completed regression in the development "
    "environment but cannot sign off without staging parity, including the new "
    "webhook retry logic and updated tax calculation module. Attached to the original "
    "ticket are HAR exports from Chrome and Firefox, plus correlation identifiers from "
    "failed login attempts at 09:14, 09:27, and 10:02 UTC on March fourth. No "
    "changes were made to our VPN, firewall rules, or local DNS. Other vendors on "
    "the shared identity tenant report no issues. Please escalate if restoration "
    "requires coordination with the identity team. We have a change advisory board "
    "meeting tomorrow and need a concrete restoration ETA or a temporary workaround "
    "such as local break-glass accounts with audit logging enabled."
)
